spring:
  application:
    name: picky-be
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:mysql://${DB_HOST:db}:3306/picky?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowLoadLocalInfile=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update   # update create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

  data:
    mongodb:
      uri: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/${MONGO_DATABASE}?authSource=admin

    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            scope: openid, email, profile
            redirect-uri: "${GOOGLE_OAUTH_BASE_URL}/login/oauth2/code/{registrationId}"
        provider:
          google:
            issuer-uri: https://accounts.google.com


jwt:
  secret: ${JWT_SECRET}
  issuer: picky
  access-token-validity-seconds: 1800
  refresh-token-validity-seconds: 1209600

logging:
  level:
    com.c102.picky: DEBUG

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
  oauth:
    google:
      web-client-id: ${GOOGLE_OAUTH_CLIENT_ID}
      chrome-extension-client-id: ${CHROME_EXTENSION_GOOGLE_CLIENT_ID}
  cookie:
    name: ${APP_COOKIE_NAME}
    domain: ${APP_COOKIE_DOMAIN}
    path: ${APP_COOKIE_PATH}
    http-only: ${APP_COOKIE_HTTP_ONLY}
    secure: ${APP_COOKIE_SECURE}
    same-site: ${APP_COOKIE_SAME_SITE}
    max-age: ${APP_COOKIE_MAX_AGE}
  seed:
    csv-path: ${APP_SEED_CSV_PATH:/app/data/quiz_wiki_all.csv}
    line-ending: CRLF
    enabled: true
    force: false  # true -> TRUNCATE 후 강제 재적재
    categories:
      enabled: true
  mongodb:
    browsing-prefix: ${MONGO_BROWSING_PREFIX:browsing}
    history-prefix: ${MONGO_HISTORY_PREFIX:history}
  fact-seed:
    enabled: true
    csv-path: /app/data/facts.csv   # 컨테이너 내부 경로
    line-ending: CRLF                              # 또는 LF
    force: false                                   # true면 TRUNCATE 후 재적재
