spring:
  application:
    name: picky-be

  datasource:
    url: jdbc:mysql://db:3306/picky?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update   # update create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

  data:
    mongodb:
      uri: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/${MONGO_DATABASE}?authSource=admin

    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "89436861621-nkkljkj1to3m7j2dl3v4kde6pja9s5p7.apps.googleusercontent.com"
            client-secret: "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"
            scope: openid, email, profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
        provider:
          google:
            issuer-uri: https://accounts.google.com


jwt:
  secret: iQWWa9DnaANYkLCRPccRChAeuQt7owLnAwucLKCxR3A=
  issuer: picky
  access-token-validity-seconds: 1800
  refresh-token-validity-seconds: 1209600
